"""Core Verb Atlas — the 32 Month-1 verbs as usable systems, not just tables.

Present forms are embedded so the drill engine is self-contained (the
`conjugations` table has the full verbecc paradigms for every other tense).
Spanish forms power ES→FR prompts and the translation ladder.
"""

from __future__ import annotations

from dataclasses import dataclass

PERSONS = ("1s", "2s", "3s", "1p", "2p", "3p")


@dataclass(frozen=True)
class CoreVerb:
    id: str
    infinitive: str
    spanish: str
    english: str
    sprint: int
    ipa: str
    group: str  # er | ir | re | irregular
    present: tuple[str, str, str, str, str, str]  # je tu il nous vous ils
    participle: str
    auxiliary: str  # avoir | être
    es_infinitive: str
    es_present: tuple[str, str, str, str, str, str]  # yo tú él nosotros vosotros ellos
    es_participle: str
    family: str = ""
    constructions: tuple[tuple[str, str], ...] = ()
    examples: tuple[tuple[str, str], ...] = ()
    prepositions: str = ""
    pronunciation: str = ""
    notes: str = ""

    def form(self, person: str) -> str:
        return self.present[PERSONS.index(person)]

    def es_form(self, person: str) -> str:
        return self.es_present[PERSONS.index(person)]

    def as_dict(self) -> dict:
        return {
            "id": self.id,
            "infinitive": self.infinitive,
            "spanish": self.spanish,
            "english": self.english,
            "sprint": self.sprint,
            "ipa": self.ipa,
            "group": self.group,
            "present": dict(zip(PERSONS, self.present)),
            "participle": self.participle,
            "auxiliary": self.auxiliary,
            "es_infinitive": self.es_infinitive,
            "es_present": dict(zip(PERSONS, self.es_present)),
            "es_participle": self.es_participle,
            "family": self.family,
            "constructions": [{"fr": fr, "es": es} for fr, es in self.constructions],
            "examples": [{"fr": fr, "es": es} for fr, es in self.examples],
            "prepositions": self.prepositions,
            "pronunciation": self.pronunciation,
            "notes": self.notes,
        }


def _cv(infinitive: str, **kw) -> CoreVerb:
    return CoreVerb(id=f"fr_{infinitive}", infinitive=infinitive, **kw)


CORE_VERBS: tuple[CoreVerb, ...] = (
    # ---- Sprint 1 ---------------------------------------------------------
    _cv("être", spanish="ser / estar", english="to be", sprint=1, ipa="/ɛtʁ/", group="irregular",
        present=("suis", "es", "est", "sommes", "êtes", "sont"), participle="été", auxiliary="avoir",
        es_infinitive="ser", es_present=("soy", "eres", "es", "somos", "sois", "son"), es_participle="sido",
        family="unique",
        constructions=(("être + adjectif", "ser / estar + adjetivo"), ("être de + ville", "ser de + ciudad"),
                       ("être en train de + inf (later)", "estar + gerundio")),
        examples=(("Je suis fatigué.", "Estoy cansado."), ("Tu es d'où ?", "¿De dónde eres?"),
                  ("On est en retard.", "Llegamos tarde.")),
        pronunciation="suis /sɥi/, es /ɛ/ = est /ɛ/, sont /sɔ̃/ vs son /sɔ̃/. êtes /ɛt/, liaison vous‿êtes /vuzɛt/.",
        notes="One verb for ser AND estar. Age is NOT être: j'ai 30 ans."),
    _cv("avoir", spanish="tener / haber", english="to have", sprint=1, ipa="/avwaʁ/", group="irregular",
        present=("ai", "as", "a", "avons", "avez", "ont"), participle="eu", auxiliary="avoir",
        es_infinitive="tener", es_present=("tengo", "tienes", "tiene", "tenemos", "tenéis", "tienen"), es_participle="tenido",
        family="unique",
        constructions=(("avoir + N + ans", "tener + N + años"), ("avoir faim / soif / froid / chaud", "tener hambre / sed / frío / calor"),
                       ("avoir besoin de", "necesitar"), ("avoir envie de", "tener ganas de"), ("il y a", "hay"),
                       ("avoir + participe passé", "haber + participio")),
        examples=(("J'ai 30 ans.", "Tengo 30 años."), ("Tu as le temps ?", "¿Tienes tiempo?"), ("Ils ont deux enfants.", "Tienen dos hijos.")),
        pronunciation="ai /e/, as = a /a/, ont /ɔ̃/ (≠ on). eu /y/ — not /ø/. Liaison ils‿ont /ilzɔ̃/ vs ils sont /ilsɔ̃/.",
        notes="Auxiliary of most passé composé verbs, exactly like haber."),
    _cv("aller", spanish="ir", english="to go", sprint=1, ipa="/ale/", group="irregular",
        present=("vais", "vas", "va", "allons", "allez", "vont"), participle="allé", auxiliary="être",
        es_infinitive="ir", es_present=("voy", "vas", "va", "vamos", "vais", "van"), es_participle="ido",
        family="unique — but the singular looks like Spanish ir (vais/vas/va ≈ voy/vas/va)",
        constructions=(("aller + infinitif (futur proche)", "ir a + infinitivo"), ("aller à / au / chez", "ir a"),
                       ("ça va ?", "¿qué tal? / ¿va bien?"), ("on y va", "vamos")),
        examples=(("Je vais au bureau.", "Voy a la oficina."), ("Tu vas faire quoi ?", "¿Qué vas a hacer?"),
                  ("On va manger.", "Vamos a comer.")),
        pronunciation="vais /vɛ/, vas = va /va/, vont /vɔ̃/, allez /ale/. Liaison vous‿allez, nous‿allons.",
        notes="No 'a' between aller and the infinitive: je vais manger (not *je vais à manger). Passé composé with être: je suis allé."),
    _cv("faire", spanish="hacer", english="to do / make", sprint=1, ipa="/fɛʁ/", group="irregular",
        present=("fais", "fais", "fait", "faisons", "faites", "font"), participle="fait", auxiliary="avoir",
        es_infinitive="hacer", es_present=("hago", "haces", "hace", "hacemos", "hacéis", "hacen"), es_participle="hecho",
        family="unique",
        constructions=(("faire du / de la + activité", "hacer + actividad"), ("il fait beau / chaud / froid", "hace buen tiempo / calor / frío"),
                       ("faire les courses / la cuisine", "hacer la compra / cocinar"), ("ça fait + durée", "hace + duración")),
        examples=(("Qu'est-ce que tu fais ?", "¿Qué haces?"), ("Je fais du sport.", "Hago deporte."), ("Il fait froid.", "Hace frío.")),
        pronunciation="fais = fait /fɛ/, faisons /fəzɔ̃/ (irregular ai = /ə/), faites /fɛt/, font /fɔ̃/.",
        notes="Weather with faire like hacer. faites and êtes: the two -tes forms."),

    # ---- Sprint 2 ---------------------------------------------------------
    _cv("vouloir", spanish="querer", english="to want", sprint=2, ipa="/vulwaʁ/", group="irregular",
        present=("veux", "veux", "veut", "voulons", "voulez", "veulent"), participle="voulu", auxiliary="avoir",
        es_infinitive="querer", es_present=("quiero", "quieres", "quiere", "queremos", "queréis", "quieren"), es_participle="querido",
        family="-oir modal: vouloir / pouvoir / devoir share the x-x-t singular",
        constructions=(("vouloir + infinitif", "querer + infinitivo"), ("vouloir + nom", "querer + sustantivo"),
                       ("je voudrais", "quisiera"), ("tu veux bien … ?", "¿te importa … ?")),
        examples=(("Je veux partir.", "Quiero irme."), ("Tu veux un café ?", "¿Quieres un café?"), ("Ils veulent venir.", "Quieren venir.")),
        pronunciation="veux = veut /vø/, veulent /vœl/ — the -ent is silent but the l comes back.",
        notes="Also 'to mean': ça veut dire = quiere decir — same idiom as Spanish."),
    _cv("pouvoir", spanish="poder", english="can / be able", sprint=2, ipa="/puvwaʁ/", group="irregular",
        present=("peux", "peux", "peut", "pouvons", "pouvez", "peuvent"), participle="pu", auxiliary="avoir",
        es_infinitive="poder", es_present=("puedo", "puedes", "puede", "podemos", "podéis", "pueden"), es_participle="podido",
        family="-oir modal",
        constructions=(("pouvoir + infinitif", "poder + infinitivo"), ("est-ce que je peux … ?", "¿puedo … ?"),
                       ("tu peux répéter ?", "¿puedes repetir?")),
        examples=(("Je peux venir demain.", "Puedo venir mañana."), ("On peut y aller ?", "¿Podemos ir?"),
                  ("Vous pouvez répéter ?", "¿Puede repetir?")),
        pronunciation="peux = peut /pø/, peuvent /pœv/. pouvez /puve/.",
        notes="Question form 'puis-je' exists — ignore it; use est-ce que je peux."),
    _cv("devoir", spanish="deber / tener que", english="must / have to", sprint=2, ipa="/dəvwaʁ/", group="irregular",
        present=("dois", "dois", "doit", "devons", "devez", "doivent"), participle="dû", auxiliary="avoir",
        es_infinitive="tener que", es_present=("tengo que", "tienes que", "tiene que", "tenemos que", "tenéis que", "tienen que"), es_participle="tenido que",
        family="-oir modal",
        constructions=(("devoir + infinitif", "tener que / deber + infinitivo"), ("devoir de l'argent à", "deber dinero a")),
        examples=(("Je dois travailler.", "Tengo que trabajar."), ("Tu dois partir ?", "¿Tienes que irte?"),
                  ("On doit finir ça.", "Tenemos que terminar esto.")),
        pronunciation="dois = doit /dwa/, doivent /dwav/.",
        notes="Covers both obligation (tener que) and probability (deber de)."),
    _cv("savoir", spanish="saber", english="to know (facts, how to)", sprint=2, ipa="/savwaʁ/", group="irregular",
        present=("sais", "sais", "sait", "savons", "savez", "savent"), participle="su", auxiliary="avoir",
        es_infinitive="saber", es_present=("sé", "sabes", "sabe", "sabemos", "sabéis", "saben"), es_participle="sabido",
        family="-oir",
        constructions=(("savoir + infinitif", "saber + infinitivo"), ("savoir que / si / où", "saber que / si / dónde"),
                       ("je ne sais pas", "no sé")),
        examples=(("Je sais nager.", "Sé nadar."), ("Tu sais où c'est ?", "¿Sabes dónde está?"), ("Je ne sais pas encore.", "Todavía no sé.")),
        pronunciation="sais = sait /sɛ/. savent /sav/.",
        notes="saber ↔ savoir, conocer ↔ connaître. Same split as Spanish."),
    _cv("dire", spanish="decir", english="to say / tell", sprint=2, ipa="/diʁ/", group="irregular",
        present=("dis", "dis", "dit", "disons", "dites", "disent"), participle="dit", auxiliary="avoir",
        es_infinitive="decir", es_present=("digo", "dices", "dice", "decimos", "decís", "dicen"), es_participle="dicho",
        family="-ire (lire, écrire similar)",
        constructions=(("dire que", "decir que"), ("dire à quelqu'un de + inf", "decirle a alguien que + subj"),
                       ("ça veut dire", "quiere decir"), ("on dit", "se dice")),
        examples=(("Qu'est-ce que tu dis ?", "¿Qué dices?"), ("Il dit que non.", "Dice que no."), ("Comment on dit ça ?", "¿Cómo se dice eso?")),
        pronunciation="dis = dit /di/, dites /dit/ (like faites/êtes), disent /diz/.",
        notes="dites, faites, êtes — the three irregular vous forms."),
    _cv("parler", spanish="hablar", english="to speak", sprint=2, ipa="/paʁle/", group="er",
        present=("parle", "parles", "parle", "parlons", "parlez", "parlent"), participle="parlé", auxiliary="avoir",
        es_infinitive="hablar", es_present=("hablo", "hablas", "habla", "hablamos", "habláis", "hablan"), es_participle="hablado",
        family="regular -er (the model verb)",
        constructions=(("parler + langue", "hablar + idioma"), ("parler de", "hablar de"), ("parler à / avec", "hablar con")),
        examples=(("Je parle un peu français.", "Hablo un poco de francés."), ("On parle de quoi ?", "¿De qué hablamos?"),
                  ("Tu parles trop vite.", "Hablas demasiado rápido.")),
        pronunciation="parle = parles = parlent /paʁl/ — four written forms, ONE sound. parlez = parler /paʁle/.",
        notes="THE regular -er pattern: e / es / e / ons / ez / ent."),
    _cv("penser", spanish="pensar", english="to think", sprint=2, ipa="/pɑ̃se/", group="er",
        present=("pense", "penses", "pense", "pensons", "pensez", "pensent"), participle="pensé", auxiliary="avoir",
        es_infinitive="pensar", es_present=("pienso", "piensas", "piensa", "pensamos", "pensáis", "piensan"), es_participle="pensado",
        family="regular -er",
        constructions=(("penser que", "pensar que"), ("penser à", "pensar en"), ("penser de (opinion)", "pensar de / opinar de")),
        examples=(("Je pense que oui.", "Pienso que sí."), ("Tu penses à quoi ?", "¿En qué piensas?"),
                  ("Qu'est-ce que tu en penses ?", "¿Qué opinas?")),
        pronunciation="pense /pɑ̃s/ — nasal, no /n/.",
        notes="No stem change (Spanish pienso ↔ French pense stays flat)."),
    _cv("aimer", spanish="gustar / querer", english="to like / love", sprint=2, ipa="/eme/", group="er",
        present=("aime", "aimes", "aime", "aimons", "aimez", "aiment"), participle="aimé", auxiliary="avoir",
        es_infinitive="gustar", es_present=("me gusta", "te gusta", "le gusta", "nos gusta", "os gusta", "les gusta"), es_participle="gustado",
        family="regular -er, vowel-initial (elision + liaison)",
        constructions=(("aimer + le/la/les + nom", "gustar + el/la/los/las + sustantivo"), ("aimer + infinitif", "gustar + infinitivo"),
                       ("aimer bien (like) vs aimer (love)", "caer bien / gustar vs querer"), ("j'adore", "me encanta")),
        examples=(("J'aime le café.", "Me gusta el café."), ("Tu aimes voyager ?", "¿Te gusta viajar?"),
                  ("Ils aiment bien Paris.", "Les gusta París.")),
        pronunciation="j'aime /ʒɛm/, aiment /ɛm/. Liaison: nous‿aimons, vous‿aimez, ils‿aiment /ilzɛm/.",
        notes="Subject flips: J'aime X = Me gusta X. Always a definite article after aimer."),

    # ---- Sprint 3 ---------------------------------------------------------
    _cv("venir", spanish="venir", english="to come", sprint=3, ipa="/vəniʁ/", group="irregular",
        present=("viens", "viens", "vient", "venons", "venez", "viennent"), participle="venu", auxiliary="être",
        es_infinitive="venir", es_present=("vengo", "vienes", "viene", "venimos", "venís", "vienen"), es_participle="venido",
        family="venir / tenir family (devenir, revenir)",
        constructions=(("venir de + infinitif", "acabar de + infinitivo"), ("venir de + lieu", "venir de + lugar"),
                       ("venir + infinitif", "venir a + infinitivo")),
        examples=(("Je viens de manger.", "Acabo de comer."), ("Tu viens ce soir ?", "¿Vienes esta noche?"),
                  ("Elle vient de Lyon.", "Es de Lyon.")),
        pronunciation="viens = vient /vjɛ̃/, viennent /vjɛn/ — nasal singular, oral plural. venu /vəny/.",
        notes="Passé composé with être: je suis venu. venir de = recent past, exactly acabar de."),
    _cv("prendre", spanish="tomar / coger", english="to take", sprint=3, ipa="/pʁɑ̃dʁ/", group="irregular",
        present=("prends", "prends", "prend", "prenons", "prenez", "prennent"), participle="pris", auxiliary="avoir",
        es_infinitive="tomar", es_present=("tomo", "tomas", "toma", "tomamos", "tomáis", "toman"), es_participle="tomado",
        family="prendre family (apprendre, comprendre)",
        constructions=(("prendre le métro / le train", "tomar el metro / el tren"), ("prendre un café", "tomar un café"),
                       ("prendre du temps", "llevar tiempo"), ("prendre une décision", "tomar una decisión")),
        examples=(("Je prends le métro.", "Tomo el metro."), ("Tu prends quoi ?", "¿Qué tomas?"), ("On a pris un verre.", "Tomamos algo.")),
        pronunciation="prends = prend /pʁɑ̃/, prennent /pʁɛn/. pris /pʁi/.",
        notes="comprendre and apprendre conjugate identically."),
    _cv("mettre", spanish="poner", english="to put", sprint=3, ipa="/mɛtʁ/", group="irregular",
        present=("mets", "mets", "met", "mettons", "mettez", "mettent"), participle="mis", auxiliary="avoir",
        es_infinitive="poner", es_present=("pongo", "pones", "pone", "ponemos", "ponéis", "ponen"), es_participle="puesto",
        family="mettre family (permettre, promettre)",
        constructions=(("mettre + vêtement", "ponerse + ropa"), ("mettre du temps", "tardar"), ("se mettre à + inf", "ponerse a + inf")),
        examples=(("Je mets la table.", "Pongo la mesa."), ("Ça met dix minutes.", "Tarda diez minutos."), ("J'ai mis un manteau.", "Me puse un abrigo.")),
        pronunciation="mets = met /mɛ/, mettent /mɛt/. mis /mi/.",
        notes="Not reflexive for clothes in careful French: je mets un pull."),
    _cv("voir", spanish="ver", english="to see", sprint=3, ipa="/vwaʁ/", group="irregular",
        present=("vois", "vois", "voit", "voyons", "voyez", "voient"), participle="vu", auxiliary="avoir",
        es_infinitive="ver", es_present=("veo", "ves", "ve", "vemos", "veis", "ven"), es_participle="visto",
        family="voir / croire (oi → oy before vowel)",
        constructions=(("on se voit", "nos vemos"), ("voir un film", "ver una película"), ("tu vois ?", "¿ves?")),
        examples=(("Je vois.", "Ya veo."), ("On se voit demain ?", "¿Nos vemos mañana?"), ("J'ai vu Marie hier.", "Vi a Marie ayer.")),
        pronunciation="vois = voit = voient /vwa/, voyons /vwajɔ̃/. vu /vy/.",
        notes="voir = see; regarder = watch/look at (ver la tele = regarder la télé)."),
    _cv("croire", spanish="creer", english="to believe / think", sprint=3, ipa="/kʁwaʁ/", group="irregular",
        present=("crois", "crois", "croit", "croyons", "croyez", "croient"), participle="cru", auxiliary="avoir",
        es_infinitive="creer", es_present=("creo", "crees", "cree", "creemos", "creéis", "creen"), es_participle="creído",
        family="voir / croire",
        constructions=(("croire que", "creer que"), ("je crois que oui / non", "creo que sí / no")),
        examples=(("Je crois que oui.", "Creo que sí."), ("Tu crois ?", "¿Tú crees?"), ("Je ne crois pas.", "No creo.")),
        pronunciation="crois = croit = croient /kʁwa/. cru /kʁy/.",
        notes="Same shape as voir."),
    _cv("comprendre", spanish="comprender / entender", english="to understand", sprint=3, ipa="/kɔ̃pʁɑ̃dʁ/", group="irregular",
        present=("comprends", "comprends", "comprend", "comprenons", "comprenez", "comprennent"), participle="compris", auxiliary="avoir",
        es_infinitive="entender", es_present=("entiendo", "entiendes", "entiende", "entendemos", "entendéis", "entienden"), es_participle="entendido",
        family="prendre family",
        constructions=(("je ne comprends pas", "no entiendo"), ("comprendre que", "entender que")),
        examples=(("Je ne comprends pas.", "No entiendo."), ("Tu comprends ?", "¿Entiendes?"), ("J'ai compris.", "Entendido.")),
        pronunciation="comprends /kɔ̃pʁɑ̃/ — two nasals. compris /kɔ̃pʁi/.",
        notes="FR entendre = oír (faux ami)."),
    _cv("trouver", spanish="encontrar / parecer", english="to find / think (opinion)", sprint=3, ipa="/tʁuve/", group="er",
        present=("trouve", "trouves", "trouve", "trouvons", "trouvez", "trouvent"), participle="trouvé", auxiliary="avoir",
        es_infinitive="encontrar", es_present=("encuentro", "encuentras", "encuentra", "encontramos", "encontráis", "encuentran"), es_participle="encontrado",
        family="regular -er",
        constructions=(("trouver que", "parecerle a uno que"), ("trouver + objet + adjectif", "encontrar + objeto + adjetivo"),
                       ("se trouver", "encontrarse / estar")),
        examples=(("Je trouve ça bien.", "Me parece bien."), ("Tu trouves ?", "¿Tú crees?"), ("J'ai trouvé un appart.", "Encontré un piso.")),
        pronunciation="trouve /tʁuv/.",
        notes="je trouve que = me parece que — the everyday opinion verb."),
    _cv("donner", spanish="dar", english="to give", sprint=3, ipa="/dɔne/", group="er",
        present=("donne", "donnes", "donne", "donnons", "donnez", "donnent"), participle="donné", auxiliary="avoir",
        es_infinitive="dar", es_present=("doy", "das", "da", "damos", "dais", "dan"), es_participle="dado",
        family="regular -er",
        constructions=(("donner quelque chose à quelqu'un", "dar algo a alguien"), ("ça donne envie", "dan ganas")),
        examples=(("Tu peux me donner ça ?", "¿Me puedes dar eso?"), ("Je te donne mon numéro.", "Te doy mi número.")),
        pronunciation="donne /dɔn/.",
        notes="Same argument structure as dar."),
    _cv("demander", spanish="preguntar / pedir", english="to ask", sprint=3, ipa="/dəmɑ̃de/", group="er",
        present=("demande", "demandes", "demande", "demandons", "demandez", "demandent"), participle="demandé", auxiliary="avoir",
        es_infinitive="preguntar", es_present=("pregunto", "preguntas", "pregunta", "preguntamos", "preguntáis", "preguntan"), es_participle="preguntado",
        family="regular -er",
        constructions=(("demander quelque chose à quelqu'un", "pedir / preguntar algo a alguien"),
                       ("demander si / où", "preguntar si / dónde"), ("se demander", "preguntarse")),
        examples=(("Je peux te demander quelque chose ?", "¿Te puedo preguntar algo?"),
                  ("Il demande où c'est.", "Pregunta dónde está."), ("J'ai demandé l'addition.", "Pedí la cuenta.")),
        pronunciation="demande /dəmɑ̃d/.",
        notes="Faux ami: ES demandar = to sue."),
    _cv("répondre", spanish="responder / contestar", english="to answer", sprint=3, ipa="/ʁepɔ̃dʁ/", group="re",
        present=("réponds", "réponds", "répond", "répondons", "répondez", "répondent"), participle="répondu", auxiliary="avoir",
        es_infinitive="contestar", es_present=("contesto", "contestas", "contesta", "contestamos", "contestáis", "contestan"), es_participle="contestado",
        family="regular -re (attendre, entendre, vendre)",
        constructions=(("répondre à quelqu'un / à un message", "responder a alguien / a un mensaje"),),
        examples=(("Il ne répond pas.", "No contesta."), ("Je réponds ce soir.", "Contesto esta noche."), ("Tu as répondu ?", "¿Contestaste?")),
        pronunciation="réponds = répond /ʁepɔ̃/, répondent /ʁepɔ̃d/.",
        notes="Regular -re: s / s / – / ons / ez / ent. Always à."),

    # ---- Sprint 4 ---------------------------------------------------------
    _cv("vivre", spanish="vivir", english="to live", sprint=4, ipa="/vivʁ/", group="irregular",
        present=("vis", "vis", "vit", "vivons", "vivez", "vivent"), participle="vécu", auxiliary="avoir",
        es_infinitive="vivir", es_present=("vivo", "vives", "vive", "vivimos", "vivís", "viven"), es_participle="vivido",
        family="unique",
        constructions=(("vivre à / en", "vivir en"), ("vivre avec", "vivir con"), ("vivre de", "vivir de")),
        examples=(("Je vis à Chicago.", "Vivo en Chicago."), ("Ils vivent ensemble.", "Viven juntos."), ("J'ai vécu à Boston.", "Viví en Boston.")),
        pronunciation="vis = vit /vi/, vivent /viv/. vécu /veky/.",
        notes="habiter = reside (address); vivre = live (life)."),
    _cv("travailler", spanish="trabajar", english="to work", sprint=4, ipa="/tʁavaje/", group="er",
        present=("travaille", "travailles", "travaille", "travaillons", "travaillez", "travaillent"), participle="travaillé", auxiliary="avoir",
        es_infinitive="trabajar", es_present=("trabajo", "trabajas", "trabaja", "trabajamos", "trabajáis", "trabajan"), es_participle="trabajado",
        family="regular -er",
        constructions=(("travailler dans / chez / pour", "trabajar en / para"), ("travailler comme", "trabajar de / como")),
        examples=(("Je travaille chez moi.", "Trabajo desde casa."), ("Tu travailles demain ?", "¿Trabajas mañana?"),
                  ("J'ai travaillé tard.", "Trabajé hasta tarde.")),
        pronunciation="travaille /tʁavaj/ — -aill = /aj/, the ll is a glide.",
        notes="The model sentence verb: Je veux travailler demain."),
    _cv("rester", spanish="quedarse", english="to stay", sprint=4, ipa="/ʁɛste/", group="er",
        present=("reste", "restes", "reste", "restons", "restez", "restent"), participle="resté", auxiliary="être",
        es_infinitive="quedarse", es_present=("me quedo", "te quedas", "se queda", "nos quedamos", "os quedáis", "se quedan"), es_participle="quedado",
        family="regular -er, être auxiliary",
        constructions=(("rester à la maison / ici", "quedarse en casa / aquí"), ("il reste + N", "queda(n) + N")),
        examples=(("Je reste ici.", "Me quedo aquí."), ("On reste combien de temps ?", "¿Cuánto tiempo nos quedamos?"),
                  ("Je suis resté chez moi.", "Me quedé en casa.")),
        pronunciation="reste /ʁɛst/.",
        notes="Not reflexive. Faux ami: ES restar."),
    _cv("partir", spanish="irse / salir", english="to leave", sprint=4, ipa="/paʁtiʁ/", group="ir",
        present=("pars", "pars", "part", "partons", "partez", "partent"), participle="parti", auxiliary="être",
        es_infinitive="irse", es_present=("me voy", "te vas", "se va", "nos vamos", "os vais", "se van"), es_participle="ido",
        family="-ir short family (sortir, dormir, sentir): drop the stem consonant in the singular",
        constructions=(("partir à / en / pour", "irse a"), ("partir de", "salir de"), ("partir en vacances", "irse de vacaciones")),
        examples=(("Je pars demain.", "Me voy mañana."), ("Tu pars à quelle heure ?", "¿A qué hora te vas?"),
                  ("Elle est partie tôt.", "Se fue temprano.")),
        pronunciation="pars = part /paʁ/, partent /paʁt/.",
        notes="Passé composé with être, participle agrees: elle est partie."),
    _cv("arriver", spanish="llegar", english="to arrive / manage to", sprint=4, ipa="/aʁive/", group="er",
        present=("arrive", "arrives", "arrive", "arrivons", "arrivez", "arrivent"), participle="arrivé", auxiliary="être",
        es_infinitive="llegar", es_present=("llego", "llegas", "llega", "llegamos", "llegáis", "llegan"), es_participle="llegado",
        family="regular -er, être auxiliary, vowel-initial",
        constructions=(("arriver à + lieu", "llegar a"), ("arriver à + infinitif", "conseguir / lograr + infinitivo"),
                       ("j'arrive !", "¡ya voy!"), ("qu'est-ce qui arrive ?", "¿qué pasa?")),
        examples=(("J'arrive dans dix minutes.", "Llego en diez minutos."), ("Je n'arrive pas à dormir.", "No consigo dormir."),
                  ("On est arrivés tard.", "Llegamos tarde.")),
        pronunciation="j'arrive /ʒaʁiv/. Liaison ils‿arrivent /ilzaʁiv/.",
        notes="Passé composé with être."),
    _cv("passer", spanish="pasar", english="to pass / spend / drop by", sprint=4, ipa="/pase/", group="er",
        present=("passe", "passes", "passe", "passons", "passez", "passent"), participle="passé", auxiliary="avoir",
        es_infinitive="pasar", es_present=("paso", "pasas", "pasa", "pasamos", "pasáis", "pasan"), es_participle="pasado",
        family="regular -er (être when intransitive: je suis passé chez toi)",
        constructions=(("passer du temps", "pasar tiempo"), ("passer un bon moment", "pasarlo bien"), ("passer chez", "pasar por casa de"),
                       ("qu'est-ce qui se passe ?", "¿qué pasa?")),
        examples=(("J'ai passé un bon week-end.", "Pasé un buen finde."), ("Je passe chez toi ce soir.", "Paso por tu casa esta noche."),
                  ("Le temps passe vite.", "El tiempo pasa rápido.")),
        pronunciation="passe /pas/.",
        notes="Same broad meaning range as pasar."),
    _cv("commencer", spanish="empezar / comenzar", english="to start", sprint=4, ipa="/kɔmɑ̃se/", group="er",
        present=("commence", "commences", "commence", "commençons", "commencez", "commencent"), participle="commencé", auxiliary="avoir",
        es_infinitive="empezar", es_present=("empiezo", "empiezas", "empieza", "empezamos", "empezáis", "empiezan"), es_participle="empezado",
        family="regular -er (spelling: -çons)",
        constructions=(("commencer à + infinitif", "empezar a + infinitivo"), ("commencer par", "empezar por")),
        examples=(("Je commence à 9 h.", "Empiezo a las 9."), ("On commence ?", "¿Empezamos?"), ("J'ai commencé hier.", "Empecé ayer.")),
        pronunciation="commence /kɔmɑ̃s/, commençons /kɔmɑ̃sɔ̃/.",
        notes="à + infinitive, like empezar a."),
    _cv("finir", spanish="terminar / acabar", english="to finish", sprint=4, ipa="/finiʁ/", group="ir",
        present=("finis", "finis", "finit", "finissons", "finissez", "finissent"), participle="fini", auxiliary="avoir",
        es_infinitive="terminar", es_present=("termino", "terminas", "termina", "terminamos", "termináis", "terminan"), es_participle="terminado",
        family="regular -ir (-iss- plural: choisir, réussir)",
        constructions=(("finir de + infinitif", "terminar de + infinitivo"), ("c'est fini", "se acabó"), ("finir par", "acabar por / terminar + gerundio")),
        examples=(("Je finis à 18 h.", "Termino a las 6."), ("Tu as fini ?", "¿Terminaste?"), ("On finit ça demain.", "Terminamos esto mañana.")),
        pronunciation="finis = finit /fini/, finissent /finis/.",
        notes="The -iss- verbs: the true regular -ir group."),
    _cv("essayer", spanish="intentar / probar", english="to try", sprint=4, ipa="/eseje/", group="er",
        present=("essaie", "essaies", "essaie", "essayons", "essayez", "essaient"), participle="essayé", auxiliary="avoir",
        es_infinitive="intentar", es_present=("intento", "intentas", "intenta", "intentamos", "intentáis", "intentan"), es_participle="intentado",
        family="-yer (y → i in singular / 3p)",
        constructions=(("essayer de + infinitif", "intentar + infinitivo"), ("essayer + nom", "probar + sustantivo")),
        examples=(("J'essaie de parler français.", "Intento hablar francés."), ("Essaie !", "¡Inténtalo!"), ("J'ai essayé.", "Lo intenté.")),
        pronunciation="essaie /esɛ/, essayons /esejɔ̃/.",
        notes="de + infinitive (Spanish has none: intentar hablar)."),
    _cv("sentir", spanish="sentir(se) / oler", english="to feel / smell", sprint=4, ipa="/sɑ̃tiʁ/", group="ir",
        present=("sens", "sens", "sent", "sentons", "sentez", "sentent"), participle="senti", auxiliary="avoir",
        es_infinitive="sentirse", es_present=("me siento", "te sientes", "se siente", "nos sentimos", "os sentís", "se sienten"), es_participle="sentido",
        family="-ir short family (partir, sortir, dormir)",
        constructions=(("se sentir + adjectif", "sentirse + adjetivo"), ("sentir + odeur", "oler a"), ("ça sent bon", "huele bien")),
        examples=(("Je me sens bien.", "Me siento bien."), ("Tu te sens comment ?", "¿Cómo te sientes?"), ("Ça sent bon !", "¡Huele bien!")),
        pronunciation="sens = sent /sɑ̃/, sentent /sɑ̃t/.",
        notes="Reflexive for feelings (se sentir), plain for smell."),
)

CORE_VERBS_BY_ID: dict[str, CoreVerb] = {v.id: v for v in CORE_VERBS}
CORE_VERBS_BY_INF: dict[str, CoreVerb] = {v.infinitive: v for v in CORE_VERBS}


def verbs_for_sprint(sprint: int) -> list[CoreVerb]:
    return [v for v in CORE_VERBS if v.sprint == sprint]


def verbs_through_sprint(sprint: int) -> list[CoreVerb]:
    return [v for v in CORE_VERBS if v.sprint <= sprint]
